#!/usr/bin/env python

import os.path
import sys

# look for local lib too
plover_dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), "../")
sys.path.insert(0, plover_dir)

from plover.main import main

main()

